apiVersion: apps/v1
kind: Deployment
metadata:
  name: lnf-client-service
  namespace: lnf-develop
  labels:
    app: lnf-client-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lnf-client-service
  template:
    metadata:
      labels:
        app: lnf-client-service
    spec:
      containers:
        - name: lnf-client-service
          image: "docker.io/levernfulcrum/lnf-client-service:{{BUILD_NUMBER}}"
          imagePullPolicy: Always
          env:
            - name: DATABASE_HOST
              value: lnf-develop-db-postgresql
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "client_db"
            - name: DATABASE_USERNAME
              value: "client_user"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: EMPLOYEE_SERVICE_URL
              value: "http://lnf-employee-service:8085/api/v1"
            - name: KEYCLOAK_HOST
              value: keycloak:8080
            - name: CLIENT-SECRET
              value: "ae3344f0-3757-4f5a-b3be-ee29276bec06"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: CLIENT_DATABASE_PASSWORD
                  name: lnf-cred
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: lnf-client-service
  namespace: lnf-develop
  labels:
    app: lnf-client-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8081
      nodePort: 32255
  selector:
    app: lnf-client-service
