alter table if exists agreement drop constraint if exists FKd9acygs81mpy54fqjxx97wl8i;
alter table if exists client_address drop constraint if exists FK8syw6n1lu2fspywj86fumxb9i;
alter table if exists client_contact drop constraint if exists FKfa5pyewnrlw9312tu8no1wvnh;
alter table if exists client_directory drop constraint if exists FKt9ymbb5lwm5ehe10ysjc0s2g7;
alter table if exists client_document drop constraint if exists FKo4td6wol5f76jfhx4sh6lq19m;
alter table if exists client_notes drop constraint if exists FK5twuolbrrme6rd5l1qhnpvvga;
alter table if exists escalation drop constraint if exists FK4ayr8whrljeemcwas53yv19y3;
alter table if exists gst drop constraint if exists FKiidilglyevfpsh6yatha2dbyf;
alter table if exists project drop constraint if exists FK8nw995uro0115f1go0dmrtn2d;
alter table if exists project_employee drop constraint if exists FK1907nkisp2dlsswuycpnakiv8;
alter table if exists project_task_employee drop constraint if exists FK7puldjwjq5vbjg8bedrxc9hvk;
alter table if exists project_task_employee drop constraint if exists FKk8gkdbu0m4vgc6lut73lrve7r;
alter table if exists statement_of_work drop constraint if exists FKn09g8kd3kb2x6v9oej0mskqk0;
alter table if exists task drop constraint if exists FKk8qrwowg31kx7hp93sru1pdqa;
drop table if exists agreement cascade;
drop table if exists client cascade;
drop table if exists client_address cascade;
drop table if exists client_contact cascade;
drop table if exists client_directory cascade;
drop table if exists client_document cascade;
drop table if exists client_notes cascade;
drop table if exists escalation cascade;
drop table if exists gst cascade;
drop table if exists project cascade;
drop table if exists project_employee cascade;
drop table if exists project_task_employee cascade;
drop table if exists statement_of_work cascade;
drop table if exists task cascade;
